# Generated by Django 4.1.5 on 2023-06-22 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_venta_detalleventa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 22, 16, 18, 22, 490650)
            ),
        ),
    ]
