# Generated by Django 4.1.5 on 2023-07-05 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_venta_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 5, 15, 16, 29, 888040)
            ),
        ),
    ]
